version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Install the package and dependencies required to build documentation
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
