# .readthedocs.yaml
version: 2

# Set the version of Python and other tools you might need
# https://github.com/python-poetry/poetry/issues/754#issuecomment-1111871973
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - python -m pip install --upgrade pip
      - python -m pip install poetry
      - python -m poetry config virtualenvs.create false
#    post_install:
      - python -m poetry install --only docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true